updates

diff --git a/fedora/.local/bin/openfiles b/fedora/.local/bin/openfiles
--- a/fedora/.local/bin/openfiles
+++ b/fedora/.local/bin/openfiles
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-if ! command -v nvim >/dev/null 2>&1; then
-  echo "Error: 'nvim' is not installed." >&2
+if ! command -v vim >/dev/null 2>&1; then
+  echo "Error: 'vim' is not installed." >&2
   exit 1
 fi
 
@@ -20,15 +20,15 @@ count=$#
 
 case "$count" in
 2)
-  ${EDITOR:-nvim} -O +'silent! normal g;' "$@" -c 'wincmd t'
+  ${EDITOR:-vim} -O +'silent! normal g;' "$@" -c 'wincmd t'
   ;;
 3)
-  ${EDITOR:-nvim} -O "$1" -c 'wincmd j' -c "silent! vsplit $2" -c "silent! split $3" -c 'wincmd t'
+  ${EDITOR:-vim} -O "$1" -c 'wincmd j' -c "silent! vsplit $2" -c "silent! split $3" -c 'wincmd t'
   ;;
 4)
-  ${EDITOR:-nvim} -O "$1" -c "silent! vsplit $2" -c "silent! split $3" -c 'wincmd h' -c "silent! split $4" -c 'wincmd t'
+  ${EDITOR:-vim} -O "$1" -c "silent! vsplit $2" -c "silent! split $3" -c 'wincmd h' -c "silent! split $4" -c 'wincmd t'
   ;;
 *)
-  ${EDITOR:-nvim} "$@"
+  ${EDITOR:-vim} "$@"
   ;;
 esac
