Init

diff --git a/ar/.local/bin/ecrypt b/ar/.local/bin/ecrypt
--- a/ar/.local/bin/ecrypt
+++ b/ar/.local/bin/ecrypt
@@ -2,13 +2,37 @@
 
 mount_luks() {
     if ! mount | grep -q " /mnt/second "; then
-        SIZE_NVME0=$(sudo blockdev --getsize64 /dev/nvme0n1p1)
-        SIZE_NVME1=$(sudo blockdev --getsize64 /dev/nvme1n1p1)
-        if [ ! -z "$SIZE_NVME0" ] && [ ! -z "$SIZE_NVME1" ]; then
-            [ "$SIZE_NVME1" -lt "$SIZE_NVME0" ] && TARGET_DEVICE="/dev/nvme0n1p1" || TARGET_DEVICE="/dev/nvme1n1p1"
-            ${TERMINAL:-st} -n floatterm -g 60x1 -e sudo cryptsetup open "$TARGET_DEVICE" "second"
-            sudo -A mount "/dev/mapper/second" "/mnt/second" -o uid="$(id -u)",gid="$(id -g)" || sudo -A mount "/dev/mapper/second" "/mnt/second"
-        fi
+        # Check for drives.
+        lsblkoutput="$(sudo lsblk -rpo "uuid,name,type,size,label,mountpoint,fstype")"
+        # Get all LUKS drives
+        allluks="$(echo "$lsblkoutput" | grep crypto_LUKS)"
+        # Get a list of the LUKS drive UUIDs already decrypted.
+        decrypted="$(find /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-* | sed "s|.*LUKS2-||;s|-.*||")"
+        # Functioning for formatting drives correctly for dmenu:
+        filter() { sed "s/ /:/g" | awk -F':' '$7==""{printf "%s%s (%s) %s\n",$1,$3,$5,$6}'; }
+
+        # Get only LUKS drives that are not decrypted.
+        unopenedluks="$(echo "$allluks" | while IFS='
+        ' read -r drive; do
+            uuid="${drive%% *}"
+            uuid="$(echo $uuid | awk -F' ' '{print $1}')"
+            [ -n "$decrypted" ] && for open in $decrypted; do
+                [ "$uuid" = "$open" ] && break 1
+            done && continue 1
+            echo " $drive"
+        done | filter)"
+       
+        # Add all to one variable. If no mountable drives found, exit.
+        luks="$(echo "$unopenedluks" | sed "/^$/d;s/ *$//")"
+        # Quit the script if a sequential command fails.
+        set -e
+        test -n "$luks"
+
+        target="$(echo "$luks" | grep 'second' | awk -F' ' '{print $1}')"
+
+        ${TERMINAL:-st} -n floatterm -g 60x1 -e sudo cryptsetup open "$target" "second"
+        echo "target: $target"
+        sudo -A mount "/dev/mapper/second" "/mnt/second" -o uid="$(id -u)",gid="$(id -g)" || sudo -A mount "/dev/mapper/second" "/mnt/second"
     fi
 }
 
@@ -27,7 +51,7 @@ attempt_mount() {
         FNEK_SIG=$ECRYPTFS_SIG
         PASSPHRASE=$(pass show encryption/ecryptfs)
         [ -z "$PASSPHRASE" ] && { notify-send "❌ Failed to retrieve passphrase."; exit 1; }
-        mount_luks && mount_encrypted "$1" "$2" && notify-send "📂 Unlocked: $3" || notify-send "❌ Failed to unlock: $3"
+        mount_luks && mount_encrypted "$1" "$2" && notify-send "📂 Unlocked: $3" || notify-send "⛔ Failed to unlock: $3"
     fi
 }
 
