modified iwaf

diff --git a/ar/.local/bin/iwaf b/ar/.local/bin/iwaf
--- a/ar/.local/bin/iwaf
+++ b/ar/.local/bin/iwaf
@@ -39,7 +39,12 @@ if ! command -v winetricks >/dev/null; then
         exit 1
     }
 fi
-winetricks -q mfc42 >/dev/null 2>&1
+
+echo "Installing required libraries via winetricks..."
+if ! winetricks -q vcrun2005 mfc42; then
+    echo "Failed to install required libraries!"
+    exit 1
+fi
 
 # Run the SOOP Streamer installer without sudo
 echo 'Running the SOOP Streamer installer...'
