modified gitupdate, modified passmenu2

diff --git a/ar/.local/bin/passmenu2 b/ar/.local/bin/passmenu2
--- a/ar/.local/bin/passmenu2
+++ b/ar/.local/bin/passmenu2
@@ -1,22 +1,22 @@
-#!/bin/sh
+#!/bin/bash
 
 shopt -s nullglob globstar
 
 typeit=0
 if [[ $1 == "--type" ]]; then
-	typeit=1
-	shift
+    typeit=1
+    shift
 fi
 
 if [[ -n $WAYLAND_DISPLAY ]]; then
-	dmenu_cmd="dmenu-wl -l 20"
-	xdotool="ydotool type --file -"
+    dmenu_cmd="dmenu-wl -l 20"
+    xdotool="ydotool type --file -"
 elif [[ -n $DISPLAY ]]; then
-	dmenu_cmd="dmenu -l 20"
-	xdotool="xdotool type --clearmodifiers --file -"
+    dmenu_cmd="dmenu -l 20"
+    xdotool="xdotool type --clearmodifiers --file -"
 else
-	echo "Error: No Wayland or X11 display detected" >&2
-	exit 1
+    echo "Error: No Wayland or X11 display detected" >&2
+    exit 1
 fi
 
 prefix=${PASSWORD_STORE_DIR-~/.password-store}
@@ -29,10 +29,10 @@ password=$(printf '%s\n' "${password_files[@]}" | $dmenu_cmd "$@")
 [[ -n $password ]] || exit
 
 if [[ $typeit -eq 0 ]]; then
-	pass show -c "$password" 2>/dev/null
+    pass show -c "$password" 2>/dev/null
 else
-	pass show "$password" | {
-		IFS= read -r pass
-		printf %s "$pass"
-	} | $xdotool
+    pass show "$password" | {
+        IFS= read -r pass
+        printf %s "$pass"
+    } | $xdotool
 fi
