modified zsh/keymaps.zsh, modified bin/hugow, modified bin/rbackup, modified Music/.music.txt

diff --git a/ar/.local/bin/rbackup b/ar/.local/bin/rbackup
--- a/ar/.local/bin/rbackup
+++ b/ar/.local/bin/rbackup
@@ -178,10 +178,10 @@ echo "Backup starts to $backup_path..."
 process_options "$@"
 
 # Main script logic
-mount_luks && echo "Mount backup drive... " && echo "Success to mount luks drive!" || error "Failed to mount $backup_path"
+#mount_luks && echo "Mount backup drive... " && echo "Success to mount luks drive!" || error "Failed to mount $backup_path"
 [ -d "$backup_path" ] || sudo mkdir -p "$backup_path"
 echo "Sync home files..." && sync_files && echo "Success to sync files!" || error "Failed back up files"
 echo "Sync root files..." && sync_root && echo "Success to sync root!" || error "Failed back up root"
 echo "Sync server files..." && sync_server && echo "Success to sync server!" || error "Failed back up server"
-echo "Sync files to nextcloud..." && sync_nextcloud && echo "Success to sync nextcloud!" || error "Failed back up nextcloud"
+#echo "Sync files to nextcloud..." && sync_nextcloud && echo "Success to sync nextcloud!" || error "Failed back up nextcloud"
 echo "Done!"
